# Generated by Django 3.1.3 on 2021-03-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_department'),
        ('api', '0016_auto_20201215_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='department',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='extra_data',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='mode',
            field=models.CharField(choices=[('kiosk', 'Kiosk Mode'), ('redirect', 'Redirect Mode'), ('info_page', 'Information Page Mode'), ('chance', 'Chance based redirect')], default='redirect', help_text='\nSets the mode this code is in.<br/>\nKiosk Mode: Show buttons to choose a link from<br/>\nRedirect Mode: Instantly redirects to the url with the highest priority.<br/>\nInformation Page Mode: Show basic info with links to different urls.<br/>\nChance based redirect: will redirect to one of the urls, based on priority proportion. \n', max_length=16),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
